name: image_denoising_app
environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  before_after: ^3.1.0   # ğŸ‘ˆ split slider package
